apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 3
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: flockdb
      owner: flockuser
      secret:
        name: flockuser-secret
      postInitSQL:
        - ALTER ROLE flockuser WITH LOGIN;
